package com.lifeblueprint.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.commonmark.node.Node;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private final JavaMailSender mailSender;
    private final Parser mdParser;
    private final HtmlRenderer mdRenderer;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
        this.mdParser = Parser.builder().build();
        this.mdRenderer = HtmlRenderer.builder().build();
    }

    public void sendReport(String to, String reportId, String reportText, String displayName) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom("fyk827827@gmail.com");
            helper.setTo(to);
            helper.setSubject("Your Life Blueprint Report is Ready");

            String html = buildReportEmail(reportId, displayName);
            helper.setText(html, true);

            mailSender.send(message);
            System.out.println("[EmailService] Report email sent successfully to " + to);
        } catch (MessagingException e) {
            System.err.println("[EmailService] Failed to send report email to " + to + ": " + e.getMessage());
            throw new RuntimeException("Failed to send email: " + e.getMessage(), e);
        }
    }

    public void sendTestEmail(String to) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");

            helper.setFrom("fyk827827@gmail.com");
            helper.setTo(to);
            helper.setSubject("PRISM - Test Email");
            helper.setText("This is a test email from PRISM Life Script.\n\nIf you received this, SMTP is working correctly.\n\nTimestamp: " + System.currentTimeMillis(), false);

            mailSender.send(message);
            System.out.println("[EmailService] Test email sent successfully to " + to);
        } catch (MessagingException e) {
            System.err.println("[EmailService] Failed to send test email to " + to + ": " + e.getMessage());
            throw new RuntimeException("Failed to send test email: " + e.getMessage(), e);
        }
    }

    private String buildReportEmail(String reportId, String displayName) {
        String name = displayName != null && !displayName.isBlank() ? displayName : "Your Report";
        String date = java.time.LocalDate.now().toString();
        String reportUrl = "https://divinlove.com/generator/final-report?reportId=" + reportId;

        return """
            <!DOCTYPE html>
            <html>
            <head><meta charset="utf-8"/>
            <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { font-family: 'Helvetica Neue', Arial, sans-serif; background: #0D1B2A; color: #E8DCC8; padding: 0; }
              .wrap { max-width: 520px; margin: 0 auto; background: #1A0F2E; border-radius: 12px; overflow: hidden; }
              .header { text-align: center; padding: 36px 32px 24px; background: linear-gradient(135deg, #2D1B4E 0%, #1A0F2E 100%); }
              .header h1 { color: #E8C87A; font-size: 22px; font-weight: 700; letter-spacing: 2px; margin: 0 0 4px; }
              .header p { color: rgba(232,220,200,0.5); font-size: 12px; margin: 0; }
              .body { padding: 32px; text-align: center; }
              .body p { font-size: 14px; line-height: 1.7; margin: 0 0 12px; color: #E8DCC8; }
              .btn { display: inline-block; padding: 14px 36px; margin-top: 8px;
                     background: linear-gradient(135deg, #E8C87A, #D4A84B); color: #1A0F2E;
                     text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 600; }
              .footer { text-align: center; padding: 16px 32px 24px; border-top: 1px solid rgba(232,200,122,0.1); }
              .footer p { font-size: 11px; color: rgba(232,220,200,0.25); margin: 0; }
            </style></head>
            <body>
              <div class="wrap">
                <div class="header">
                  <h1>Your Life Blueprint</h1>
                  <p>__NAME__ · __DATE__</p>
                </div>
                <div class="body">
                  <p>Your Life Blueprint Report is ready.</p>
                  <p>Click the button below to view your full report online.</p>
                  <a href="__URL__" class="btn">View Your Full Report →</a>
                </div>
                <div class="footer">
                  <p>Generated by PRISM Life Script</p>
                </div>
              </div>
            </body>
            </html>
            """
            .replace("__NAME__", name)
            .replace("__DATE__", date)
            .replace("__URL__", reportUrl);
    }

    private String mdToHtml(String md) {
        if (md == null || md.isBlank()) return "";
        Node document = mdParser.parse(md);
        return mdRenderer.render(document);
    }
}
